services:
  django:
    build: ./GradingAgentFrontend
    environment:
      - FASTAPI_URL=http://fastapi:8001
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - fastapi
      - db

  fastapi:
    build: ./GradingAgentAPI
    environment:
      - ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    ports:
      - "8001:8001"
    depends_on:
      - db      

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  postgres_data:
